name: loader_animated
description: Dart package that helps developers to show lowding widget in Apps.
version: 0.0.2
homepage: "https://github.com/Rajkumar07793/loader"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
